"""confirmation migration

Revision ID: 20bbf62cd706
Revises: None
Create Date: 2015-05-09 15:34:15.251755

"""

# revision identifiers, used by Alembic.
revision = '20bbf62cd706'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_details')
    op.drop_table('bugs')
    op.drop_table('company')
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    op.create_table('company',
    sa.Column('id', mysql.INTEGER(display_width=10), nullable=False),
    sa.Column('company_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('company_website', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('bounty_amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('autherized', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('problem_related_1', mysql.VARCHAR(length=10000), nullable=False),
    sa.Column('problem_related_2', mysql.VARCHAR(length=10000), nullable=False),
    sa.Column('problem_related_3', mysql.VARCHAR(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('bugs',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('bugs_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('bugs_bounty', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('bugs_company', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('bugs_recognised_time', sa.DATE(), nullable=False),
    sa.Column('bugs_solved_time', sa.DATE(), nullable=False),
    sa.Column('resolved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('money_transfered', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('user_details',
    sa.Column('id', mysql.INTEGER(display_width=10), nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('email_id', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('linkedin_link', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('bugs_solved', mysql.INTEGER(display_width=10), autoincrement=False, nullable=True),
    sa.Column('autherized', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('money_recived', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text(u"'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
